### ISSUE TITLE
 Arduino IDE 2.0.4  boards manager can not install gd32

### ISSUE THREAD

**Issue by QGB** [CommunityGD32Cores/ArduinoCore-GD32#85] opened 2023-04-17 19:03 UTC
![image](https://user-images.githubusercontent.com/8005654/232585252-91a95739-4ab7-4090-ac37-f08839ecd483.png)

**Comment by maxgerhardt** [comment] 2023-04-17 19:11
This is a duplicate of https://github.com/CommunityGD32Cores/ArduinoCore-GD32/issues/52#issuecomment-951212004.

There is a fundamental issue in Arduino IDE 2.0 that it does not allow not having a checksum in the board URL, which makes 0 sense for development versions. 

We'll update `CommunityGD32Cores/arduino-board-index/main/package_gd32_index.json` to the current hash.

**Closed by maxgerhardt** 2023-04-17 19:11 UTC

**Comment by maxgerhardt** [comment] 2023-04-17 19:15
Fixed in https://github.com/CommunityGD32Cores/arduino-board-index/commit/7589831e7f2ebd20190e9b030173d8bde0610d97, use the package URL
```
https://raw.githubusercontent.com/CommunityGD32Cores/arduino-board-index/main/package_gd32_index.json
```
instead.

**Comment by QGB** [comment] 2023-04-17 19:59
still 

![image](https://user-images.githubusercontent.com/8005654/232597020-055cee22-fb17-411c-8636-d06ef21fa676.png)

**Comment by maxgerhardt** [comment] 2023-04-17 20:36
Weird, I will look into it tomorrow. In the meantime PlatformIO works, see gd32-pio-projects
